
namespace: topic-copier-dev

resources:
- topic-copier-sealed-secrets.yaml
- ../../base

configMapGenerator:
- files:
  - topic-copier.properties
  name: topic-copier-configmap

generatorOptions:
  disableNameSuffixHash: true

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: image-registry.openshift-image-registry.svc:5000/topic-copier-dev/topic-copier:latest
  target:
    kind: Deployment
    name: topic-copier
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
